import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Script from 'next/script'
import styles from '../styles/Home.module.css'
import Hello from './components/Hello'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HuntingCoder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs HuntingCoder blog" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainnav}>
        <ul>
          <Link href='/'><li>Home</li></Link>
          <Link href='/about'><li>About</li></Link>
          <Link href='/blog'><li>Blog</li></Link>
          <Link href='/contact'><li>Contact</li></Link>
        </ul>
      </nav>
      
      <main className={styles.main}>
        <Hello />
        <h1 className='mySpan'>
          Hunting Coder
        </h1>

        <p className={styles.description}>
          For hunting coder From HuntingCoder
        </p>
        
        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn JS in 2022</h3>
            <p>JS is used to design logic in web!</p>
          </div>

          <div className="blogItem">
            <h3>How to learn JS in 2022</h3>
            <p>JS is used to design logic in web!</p>
          </div>

          <div className="blogItem">
            <h3>How to learn JS in 2022</h3>
            <p>JS is used to design logic in web!</p>
          </div>

          <div className="blogItem">
            <h3>How to learn JS in 2022</h3>
            <p>JS is used to design logic in web!</p>
          </div>
        </div>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
