import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
export default function Home() {
  return (
    <div className={styles.container}>

      <style jsx>
        {`
          h2{
            font-size: 28px;
          }
          h3{
            font-size: 28px;
          }
        `}
      </style>

      <Head>
        <title>HuntingCoder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs HuntingCoder blog" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      
      <main className={styles.main}>
        <h1>
          Hunting Coder
        </h1>

        <Image className={styles.myImg} src='/coderimg.jpg' width={237} height={158} />

        <p className={styles.description}>
          For hunting coder From HuntingCoder
        </p>
        
        <div className="blogs">
          <h2>Latest Blogs</h2>
          <div className="blogItem">
            <h3>How to learn JS in 2022</h3>
            <p>JS is used to design logic in web!</p>
          </div>

          <div className="blogItem">
            <h3>How to learn JS in 2022</h3>
            <p>JS is used to design logic in web!</p>
          </div>

          <div className="blogItem">
            <h3>How to learn JS in 2022</h3>
            <p>JS is used to design logic in web!</p>
          </div>

          <div className="blogItem">
            <h3>How to learn JS in 2022</h3>
            <p>JS is used to design logic in web!</p>
          </div>
        </div>


      </main>

      
    </div>
  )
}
